# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.2
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.1
maven_group=boblovespi.glowingfriends
archives_base_name=bob-glowing-friends

# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.155.3+26.1.2
modmenu_version=18.0.1
yacl_version=3.9.6+26.1-fabric
